export { default as SamplePage } from "./SamplePage";
export { default as NotFoundPage } from "./NotFoundPage";
export { default as PostPage } from "./PostPage";
export { default as SearchPage } from "./SearchPage";
// export { default as ListPage } from "./Listpage";
export { default as DetailsPage } from "./Detailspage";
export { default as SignUpPage } from "./SignUpPage";
export { default as FindPasswordPage } from "./FindPasswordPage";
export {default as PageMain} from "./PageMain";
export {default as Mypage} from "./Mypage/Mypage";
export {default as question} from "./Mypage/question/question";
export {default as PageList} from "./PageList";
